### ISSUE TITLE
 nedokoncene Lobby 

### ISSUE THREAD

**Issue by Maros15873** [Maros15873/YoninShogi-XP#10]
- treba doplnit moznost nastavovania atributov hry:
- cas hry (pre 1 hraca)
- byoyomi (cas ktory sa hracom neustale obnovuje ked mu cas hry vyprsi)
- hra na timy (true/false)

! nastavovat to moze len jeden z hracov !
- nech je to hrac ktory danu roomku zalozil
- treba si ho preto nejak zapamatat (to zatial nie je implementovane - treba to spravit)

**Comment by krivanek06** [comment]
zatial commit > https://github.com/Maros15873/YoninShogi-XP/commit/17949185d217064a4cd02aac178027604c8ef897 
je to väčší komit, lebo som použil prettify na lobby.html

Zatial su len vykreslene elementy na nastovovanie miestnosti v lobby, ale neposielaju sa na server
