### ISSUE TITLE
triedy User a Users

### ISSUE THREAD

**Issue by Maros15873** [Maros15873/YoninShogi-XP#2]
- chaoticky konstruktor, ktory je v celom kode nejednotny
- raz sa instancia vytvara pomocou jednotlivych atributov
- inokedy sa snazi tvarit, ze si vytvaram instanciu triedy User, ktoru potom davam do Users hoci to tak vobec nie je
- trebalo by to nejak upratat a vzajomne ich spravnym sposobom prepojit

**Comment by elias29** [comment]
Pozrel som to, a tak úplne nerozumiem čo je problém:

- chaoticky konstruktor, ktory je v celom kode nejednotny - **Nenašiel som miesto kde by bol konštruktor constructor (id, name, room) nejednotný**
-raz sa instancia vytvara pomocou jednotlivych atributov
inokedy sa snazi tvarit, ze si vytvaram instanciu triedy User, ktoru potom davam do Users hoci to tak vobec nie je - ak narážaš na Server.js tak tam sa vytvára inštancia User a následne sa vkladá do Users a podľa mňa je to správne
-
