### ISSUE TITLE
Sifrovanie textu

### ISSUE THREAD

**Issue by Maros15873** [Maros15873/YoninShogi-XP#8]
- Ked sa posiela text medzi uzivatelmi tak sa posiela ako v nezmenenej podobe
- je potrebne aby sa pred odoslanim zasifroval a po doruceni odsifroval

**Comment by krivanek06** [comment]
commit > https://github.com/Maros15873/YoninShogi-XP/commit/a441a2e7b7504e4f62f13848e37b8d435f9cae7f
