### ISSUE TITLE
Strata pripojenia pri spusteni hry (game.html)

### ISSUE THREAD

**Issue by Maros15873** [Maros15873/YoninShogi-XP#9]
- ked hraci daju v lobby "start game" tak ich to vsetkych odpoji
- treba to vyriesit tak aby sa spojenie pre prechode do hry nezrusilo

**Comment by Maros15873** [comment]
- momentalne nemame vyriesene aby sme udrzali spojenie hracov s ich socketom
- ked sa hra odstartuje tak to vsetkych z roomky odpoji
- treba vyriesit to aby aj po presunuti sa na inu "stranku" (game.html) sa spojenie udrzalo a nestratili by sme unikatne idcka hracov ktore sa im priradia ked vstupuju do roomky

**Comment by krivanek06** [comment]
My robíme tzv. multi page appku (máme viacero html súborov), preto pri prechode z jedného html (login) na iný (lobby) sa automaticky connection stratí a vytvorí sa nové websocket spojenie. 
Pozri toto : https://stackoverflow.com/questions/10886910/how-to-maintain-a-websockets-connection-between-pages

Asi appku už nezmeníme na SPA, ale ani nie je potreba. Vyriešil som to tak, že na servery ID-čko usera, čo bolo predtým socket.id som to odstránil a nahradil som to UUID-čkom ktoré generujem na login.js . To UUID si tiež ukladám do localstorage a takže sa to nikdy nestratí a je rovnaké na každej stránke.

pozri si merge request: https://github.com/Maros15873/YoninShogi-XP/pull/12/files
ak si s tým spokojný mergni to. Všetko inak ide ako aj predtým.

-------------------------------------
Poznámka: keď budete potom posielať updaty hry na server, tak posielajte na meno roomky. To meno je rovnaké a vedie na to všetci hráči počúvať.
